apiVersion: batch/v1
kind: Job
metadata:
  name: fleetpulse-ingestion
spec:
  template:
    spec:
      containers:
        - name: ingestion
          image: asia-south1-docker.pkg.dev/devops-learning-505512/fleetpulse-staging-images/ingestion:v1
      restartPolicy: Never
  backoffLimit: 3
